For users
=========

Download the distribution zip (20 MB) from https://dl.dropboxusercontent.com/u/71750979/Frege/client-0.2.0.zip .
Unpack to an `<install-dir>` of your choice.

With a Java 8, run

    <install-dir>/bin/client

Additions to the use of the command-line REPL
=============================================
In addition to the commands in the command-line REPL like `:help`, the following keyboard shortcuts are supported:

    Enter      Submit the current editor content for execution
    Up         Show previous in history.
    Down       Show next in history.
    Ctrl-Enter Insert new line in editor.
    Ctrl-L     Load Frege code via file chooser dialog.
    Ctrl-B     Bigger Font.
    Ctrl-S     Smaller Font.

Beside Ctrl, you can use the Cmd key on Mac.
This feature can conflict with local keyboard settings for entering special characters.

Please note that _this GUI is not an IDE_. The content of the editor is fed line-by-line to the
command-line REPL and this limits the amount of work that one can do in "one go".

Multi-line content is automatically wrapped in `:{` and `:}` as expected by the REPL.

However, that still doesn't allow to submit multi-line definitions together with their usage:

    foo a b =
              a * b
    foo 1 2          -- will fail with "a where clause cannot start with '=' "

What works is to do the same in two steps.

Step 1

    foo a b =
              a * b

Step 2

    foo 1 2

That is something to keep in mind when copy-pasting code in the editor.



For developers
==============

With Java 8 start via

    gradlew clean :client:run


NOTE: There is no need to install gradle or anything else beside a Java 8 JDK.
      It is all self-installing.